"""Initial migration for edge_pc and alert schema changes

Revision ID: 6ee722e50a95
Revises: 
Create Date: 2026-02-19 04:35:53.029760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee722e50a95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'edge_pcs',
        sa.Column('edge_pc_id', sa.String(), nullable=False),
        sa.Column('site_name', sa.String(), nullable=False),
        sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=False, server_default='offline'),
        sa.PrimaryKeyConstraint('edge_pc_id')
    )
    op.create_table(
        'alerts',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('site_id', sa.String(), nullable=False),
        sa.Column('camera_id', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('detections', sa.JSON(), nullable=False),
        sa.Column('image_path', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('edge_pcs')
    # ### end Alembic commands ###
